### ISSUE TITLE
[super] Inflation / Price Index / PPP / Deflator data

### ISSUE THREAD

**Issue by rufuspollock** [datasets/awesome-data#18]
- Price indices
  - <del>World CPI (per country) #170</del> https://github.com/datasets/cpi 
  - Country specific price indexes e.g.
    - https://github.com/datasets/cpi-gb 
    - https://github.com/datasets/cpi-us
- Inflation
  - World: #165  
- PPP
  - <del>Global PPP #40</del> https://github.com/datasets/ppp
- Price deflators

Granularity
- Spatial:
  - "World" i.e. per country (probably annual time series)
  - Per country: probably want a sub-selection and greater granularity
- Temporal
  - Year, month, day (?)
  - Span: historical is special. For uniform values probably more recent.

**Comment by rgrp** [comment]
Re-opening as making this a "super" issue with links out to specific packages.
