### ISSUE TITLE
Harmonized System

### ISSUE THREAD

**Issue by sabas** [datasets/awesome-data#203]
Commodities coding system, called also HS Code
https://en.wikipedia.org/wiki/Harmonized_System
2017 edition
http://www.wcoomd.org/en/topics/nomenclature/instrument-and-tools/hs-nomenclature-2017-edition.aspx

**Comment by rufuspollock** [comment]
@sabas like it ...

**Comment by sabas** [comment]
I drafted the package with the supporting data and the codes from the first chapter (out of 97) manually extracted from the PDFs.
https://github.com/sabas/harmonized-system

**Comment by rufuspollock** [comment]
@pdehaye could you review @sabas work and see if it is ready for core?

**Comment by sabas** [comment]
Please only consider the structure, the main data is only from a sample chapter, and one row is not quoted

**Comment by pdehaye** [comment]
@rgrp, I am trying to focus a bit my efforts for 2017 (towards personal
data stuff). Is this a one shot, or will there be follow ups? If the latter
it makes more sense for someone else to do it. Thanks!

**Comment by rufuspollock** [comment]
@pdehaye this is a one-shot so if you could look that would be great.

regarding being managing curator: I hear you that you would like to hand the baton on ...

**Comment by sabas** [comment]
@rufuspollock I found a data source and completed the dataset
https://github.com/sabas/harmonized-system
I think it could be moved to the datasets org.

**Comment by rufuspollock** [comment]
@sabas awesome! @monikappv can you help coordinate this with @sabas

**Comment by monikappv** [comment]
@sabas hey, looks like you are a member of the datasets org - you can move the dataset directly to a new repo there.. let me know if / how I can help.

**Comment by sabas** [comment]
@monikappv done! Please have a look if that's ok
